# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3059f2d83e1dd4cd06ea27f8f791299f24bd3f3e675fb4d068ac9f89e75e3fb71583d7185a93c8bcb715087da71b921ef367a7d584b48db29166435bacbb4711

test:
  secret_key_base: 5e4cd2237026045e6d3cdde2722f7f6ed2a2f0701b871f6bc8d17a4d0485cbedf988c913d40f8a59fea99df7cc883880ffd889cf83c3b8cebb480fd20f0515af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
